-- Dos cosas: una restricción que impedía entregar las entradas de un grupo, y
-- los datos que hacen falta para auditar quién validó qué.

-- ---------------------------------------------------------------- el bloqueo

-- `tickets.order_id` se declaró `unique` en el esquema inicial, cuando una
-- compra era una silla y por lo tanto una entrada. El modelo cambió: ahora un
-- grupo compra mesas y recibe **una entrada por persona**, todas con el mismo
-- order_id. La restricción quedó y nadie la vio porque nunca se completó un
-- pago real: el webhook inserta las N entradas en un solo lote, la restricción
-- rechaza el lote entero, y el comprador se queda sin nada habiendo pagado.
--
-- Se busca por definición y no por nombre para que funcione aunque el
-- constraint se haya creado con otro nombre.
do $$
declare
  v_nombre text;
  v_attnum smallint;
begin
  select attnum into v_attnum
  from pg_attribute
  where attrelid = 'public.tickets'::regclass and attname = 'order_id';

  select con.conname into v_nombre
  from pg_constraint con
  where con.conrelid = 'public.tickets'::regclass
    and con.contype = 'u'
    and con.conkey = array[v_attnum];

  if v_nombre is not null then
    execute format('alter table public.tickets drop constraint %I', v_nombre);
    raise notice 'Quitada la restricción % : impedía más de una entrada por compra', v_nombre;
  else
    raise notice 'No había restricción única sobre tickets.order_id';
  end if;
end;
$$;

-- Lo que sí hay que impedir: dos entradas para el mismo invitado de la misma
-- compra. Si el webhook llega dos veces, esto corta la doble emisión.
create unique index if not exists tickets_una_por_invitado
  on public.tickets (order_id, guest_index)
  where guest_index is not null;

-- ---------------------------------------------------------------- auditoría

-- Número de compra legible. El uuid sirve para la máquina pero no para que dos
-- personas hablen por teléfono de la misma operación.
alter table public.orders
  add column if not exists order_number bigint generated by default as identity,
  add column if not exists paid_at timestamptz;

comment on column public.orders.order_number is
  'Número corto de la compra, para nombrarla en una auditoría o por teléfono.';
comment on column public.orders.paid_at is
  'Cuándo Mercado Pago confirmó el pago. `created_at` es cuándo se inició la compra.';

create unique index if not exists orders_numero_unico on public.orders (order_number);

-- Las entradas ya emitidas conservan el momento de pago que puedan tener.
update public.orders
set paid_at = coalesce(paid_at, updated_at)
where status = 'paid' and paid_at is null;
